config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show

  end

  def new

  end

  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Browse our Flats</h1>

<div class="cards">
  <% @flats.each do |flat| %>
    <div class="flat-card my-3">
      <img src="<%= flat.url %>" alt="<%= flat.name %>" >
      <div class="details">
        <h3><%= flat.name %></h3>
        <p><%= flat.address %></p>
        <div class="icons d-flex">
          <div class="flex mr-3">
            <i class="fas fa-user-friends mr-1"></i>
            <span><%= flat.number_of_guests %></span>
          </div>
          <div class="flex">
            <i class="fas fa-euro-sign mr-1"></i>
            <span><%= flat.price_per_night %></span>
          </div>

        </div>
      </div>
      <div class="actions">
        <%= link_to "More info", flat_path(flat), class: "blue-link" %>
        <%= link_to "Edit", "#", class: "yellow-link" %>
        <%= link_to "Remove", "#", class: "red-link" %>
      </div>
    </div>
  <% end %>
</div>
<%  %>

app/views/flats/show.html.erb
<div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1>Light &amp; Spacious Garden Flat London</h1>
        <p class="flat-show-address">10 Clifton Gardens London W9 1DT</p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p>A lovely summer feel for this spacious garden flat. Two double bedrooms, open plan living area, large kitchen and a beautiful conservatory</p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C10 Clifton Gardens London W9 1DT&key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons mr-2">people</i><span>3</span>
          </div>
          <div class="flex ml-3">
            <i class="material-icons mr-2">euro_symbol</i> 75
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa fa-facebook-square fa-2x mr-2"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar" %>
    <div class="container py-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Simple Airbnb</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/flats">Home</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <%= link_to "Add Flat", "#", class: "btn btn-outline-primary ml-2" %>
  </div>
</nav>